import { GlowLevel, MotionLevel, InterfaceProfile } from '../../types';

export const INTERFACE_PROFILES: Record<string, InterfaceProfile> = {
  focused_analysis: {
    id: 'focused_analysis',
    name: 'AUTISM PROTOCOL',
    description: 'Reduced stimulus for deep concentration and sensory-friendly market strategy.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#a0a0b0',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#1e1e2e',
      borderB: '#161625',
    },
    candles: {
      upColor: '#4ade80',
      downColor: '#f87171',
      wickUpColor: '#4ade80',
      wickDownColor: '#f87171',
      borderUpColor: '#4ade80',
      borderDownColor: '#f87171',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  emergency_relief: {
    id: 'emergency_relief',
    name: 'SENSORY RELIEF',
    description: 'Minimalist interface for high-volatility institutional moments and sensory overload.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#888888',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#222222',
      borderB: '#111111',
    },
    candles: {
      upColor: '#6b7280',
      downColor: '#9ca3af',
      wickUpColor: '#6b7280',
      wickDownColor: '#9ca3af',
      borderUpColor: '#6b7280',
      borderDownColor: '#9ca3af',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  readable_terminal: {
    id: 'readable_terminal',
    name: 'DYSLEXIA PROTOCOL',
    description: 'High legibility fonts and visual grounding for fast market reading and comprehension.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#34d399',
      downColor: '#fbbf24',
      wickUpColor: '#34d399',
      wickDownColor: '#fbbf24',
      borderUpColor: '#34d399',
      borderDownColor: '#fbbf24',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  numeric_precision: {
    id: 'numeric_precision',
    name: 'ADHD PROTOCOL',
    description: 'Visual-first data presentation and high-engagement market flows.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#60a5fa',
      downColor: '#f472b6',
      wickUpColor: '#60a5fa',
      wickDownColor: '#f472b6',
      borderUpColor: '#60a5fa',
      borderDownColor: '#f472b6',
    },
    behavior: {
      glow: 'medium',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  visual_safety: {
    id: 'visual_safety',
    name: 'Stable Data View',
    description: 'Consistent, flicker-free rendering for institutional stability.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#d1d1d1',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#2dd4bf',
      downColor: '#fb923c',
      wickUpColor: '#2dd4bf',
      wickDownColor: '#fb923c',
      borderUpColor: '#2dd4bf',
      borderDownColor: '#fb923c',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'static',
    },
  },
  assistive_feed: {
    id: 'assistive_feed',
    name: 'Visual Protocol Feed',
    description: 'Visual cues for all institutional event updates.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#e94560',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#533483',
    },
    candles: {
      upColor: '#a78bfa',
      downColor: '#fb7185',
      wickUpColor: '#a78bfa',
      wickDownColor: '#fb7185',
      borderUpColor: '#a78bfa',
      borderDownColor: '#fb7185',
    },
    behavior: {
      glow: 'low',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  workflow_support: {
    id: 'workflow_support',
    name: 'Hierarchical Analysis',
    description: 'Simplified workflow and clear tactical visual hierarchy.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#818cf8',
      downColor: '#34d399',
      wickUpColor: '#818cf8',
      wickDownColor: '#34d399',
      borderUpColor: '#818cf8',
      borderDownColor: '#34d399',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  interface_friendly: {
    id: 'interface_friendly',
    name: 'Direct Access Layout',
    description: 'Large targets and simplified institutional interactions.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#3b82f6',
      downColor: '#ef4444',
      wickUpColor: '#3b82f6',
      wickDownColor: '#ef4444',
      borderUpColor: '#3b82f6',
      borderDownColor: '#ef4444',
    },
    behavior: {
      glow: 'medium',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  dynamic_balance: {
    id: 'dynamic_balance',
    name: 'Dynamic Precision',
    description: 'Engaging but structured market feedback protocols.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#4D00FF',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#fcd34d',
      downColor: '#c084fc',
      wickUpColor: '#fcd34d',
      wickDownColor: '#c084fc',
      borderUpColor: '#fcd34d',
      borderDownColor: '#c084fc',
    },
    behavior: {
      glow: 'high',
      spacing: 'normal',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  predictable_matrix: {
    id: 'predictable_matrix',
    name: 'OCD PROTOCOL',
    description: 'Stable, symmetrical, and consistent trading interface for predictable execution.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#eeeeee',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#000000',
    },
    candles: {
      upColor: '#6ee7b7',
      downColor: '#9ca3af',
      wickUpColor: '#6ee7b7',
      wickDownColor: '#9ca3af',
      borderUpColor: '#6ee7b7',
      borderDownColor: '#9ca3af',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  high_contrast: {
    id: 'high_contrast',
    name: 'High Contrast',
    description: 'Maximum visual separation for clarity.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#000000',
      text: '#ffff00',
      accent: '#4D00FF',
      gridColor: 'rgba(255, 255, 255, 0.2)',
      borderA: '#ffffff',
      borderB: '#ffffff',
    },
    candles: {
      upColor: '#00ff00',
      downColor: '#ff0000',
      wickUpColor: '#00ff00',
      wickDownColor: '#ff0000',
      borderUpColor: '#00ff00',
      borderDownColor: '#ff0000',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  standard_trader: {
    id: 'standard_trader',
    name: 'Standard Trader',
    description: 'Classic professional trading interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#d1d4dc',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4169E1',
      downColor: '#ef4444',
      wickUpColor: '#4169E1',
      wickDownColor: '#ef4444',
      borderUpColor: '#4169E1',
      borderDownColor: '#ef4444',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  high_intensity: {
    id: 'high_intensity',
    name: 'Tactical Workspace',
    description: 'Structured, mission-critical interface for high stakes.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#94a3b8',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#1e293b',
      borderB: '#0f172a',
    },
    candles: {
      upColor: '#4d7c0f',
      downColor: '#7f1d1d',
      wickUpColor: '#4d7c0f',
      wickDownColor: '#7f1d1d',
      borderUpColor: '#4d7c0f',
      borderDownColor: '#7f1d1d',
    },
    behavior: {
      glow: 'none',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'smooth',
    },
  },
};
