
import { GlowLevel, MotionLevel, NeuroProfile } from '../../types';

export const NEURO_PROFILES: Record<string, NeuroProfile> = {
  calm_focus: {
    id: 'calm_focus',
    name: 'Calm Focus',
    description: 'Reduced stimulus for deep concentration.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#a0a0b0',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#1e1e2e',
      borderB: '#161625',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  low_stim_emergency: {
    id: 'low_stim_emergency',
    name: 'Low Stim Emergency',
    description: 'Minimalist interface for high-stress moments.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#888888',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#222222',
      borderB: '#111111',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  dyslexia_readable: {
    id: 'dyslexia_readable',
    name: 'Dyslexia Readable',
    description: 'High legibility and visual grounding.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  dyscalculia_numeric_relief: {
    id: 'dyscalculia_numeric_relief',
    name: 'Dyscalculia Numeric Relief',
    description: 'Visual-first data with reduced numeric strain.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'medium',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  visual_processing_safe: {
    id: 'visual_processing_safe',
    name: 'Visual Processing Safe',
    description: 'Stable, flicker-free rendering.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#d1d1d1',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'static',
    },
  },
  apd_assist: {
    id: 'apd_assist',
    name: 'APD Assist',
    description: 'Visual cues for auditory events.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#e94560',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#533483',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'low',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  executive_function_support: {
    id: 'executive_function_support',
    name: 'Executive Function Support',
    description: 'Simplified flow and clear visual hierarchy.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#e74c3c',
      wickUpColor: '#4D00FF',
      wickDownColor: '#e74c3c',
      borderUpColor: '#4D00FF',
      borderDownColor: '#e74c3c',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  motor_friendly: {
    id: 'motor_friendly',
    name: 'Motor Friendly',
    description: 'Large targets and simplified interactions.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ff00ff',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ff00ff',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ff00ff',
    },
    behavior: {
      glow: 'medium',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  adhd_dopamine_balanced: {
    id: 'adhd_dopamine_balanced',
    name: 'ADHD Dopamine Balanced',
    description: 'Engaging but structured visual feedback.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#4D00FF',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ff007f',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ff007f',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ff007f',
    },
    behavior: {
      glow: 'high',
      spacing: 'normal',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  adhd_hyperfocus: {
    id: 'adhd_hyperfocus',
    name: 'ADHD Hyperfocus',
    description: 'High-velocity pattern detection mode.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ffffff',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ffffff',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ffffff',
    },
    behavior: {
      glow: 'high',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  autism_predictable: {
    id: 'autism_predictable',
    name: 'Autism Predictable',
    description: 'Stable, symmetrical, and consistent interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#eeeeee',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#000000',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#393e46',
      wickUpColor: '#4D00FF',
      wickDownColor: '#393e46',
      borderUpColor: '#4D00FF',
      borderDownColor: '#393e46',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  tourette_tic_friendly: {
    id: 'tourette_tic_friendly',
    name: 'Tourette Tic Friendly',
    description: 'Low-surprise UI with stable visual rhythm.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#bbe1fa',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#3282b8',
      wickUpColor: '#4D00FF',
      wickDownColor: '#3282b8',
      borderUpColor: '#4D00FF',
      borderDownColor: '#3282b8',
    },
    behavior: {
      glow: 'low',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  plain_language: {
    id: 'plain_language',
    name: 'Plain Language',
    description: 'Simplified terminology and clear visual cues.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#e74c3c',
      wickUpColor: '#4D00FF',
      wickDownColor: '#e74c3c',
      borderUpColor: '#4D00FF',
      borderDownColor: '#e74c3c',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  high_contrast: {
    id: 'high_contrast',
    name: 'High Contrast',
    description: 'Maximum visual separation for clarity.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#000000',
      text: '#ffff00',
      accent: '#4D00FF',
      gridColor: 'rgba(255, 255, 255, 0.2)',
      borderA: '#ffffff',
      borderB: '#ffffff',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ff0000',
      wickUpColor: '#ffffff',
      wickDownColor: '#ffffff',
      borderUpColor: '#ffffff',
      borderDownColor: '#ffffff',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  custom_neuro_mix: {
    id: 'custom_neuro_mix',
    name: 'Custom Neuro Mix',
    description: 'Balanced hybrid for mixed neuro-types.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#e0e0e0',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#f44336',
      wickUpColor: '#4D00FF',
      wickDownColor: '#f44336',
      borderUpColor: '#4D00FF',
      borderDownColor: '#f44336',
    },
    behavior: {
      glow: 'low',
      spacing: 'relaxed',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  corporate_open: {
    id: 'corporate_open',
    name: 'Corporate Open',
    description: 'Clean, professional multi-chart layout.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#6c757d',
      wickUpColor: '#4D00FF',
      wickDownColor: '#6c757d',
      borderUpColor: '#4D00FF',
      borderDownColor: '#6c757d',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'high',
      motion: 'smooth',
    },
  },
  retail_chaos: {
    id: 'retail_chaos',
    name: 'Retail Chaos',
    description: 'High-intensity, high-information density.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#4D00FF',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#ff00ff',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ff0000',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ff0000',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ff0000',
    },
    behavior: {
      glow: 'high',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  retail_modular: {
    id: 'retail_modular',
    name: 'Retail Modular',
    description: 'Flexible, widget-based interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#f44336',
      wickUpColor: '#4D00FF',
      wickDownColor: '#f44336',
      borderUpColor: '#4D00FF',
      borderDownColor: '#f44336',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  vr_assistive: {
    id: 'vr_assistive',
    name: 'VR Assistive',
    description: 'Optimized for spatial computing and depth.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: 'rgba(0, 0, 0, 0.5)',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ff00ff',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ff00ff',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ff00ff',
    },
    behavior: {
      glow: 'high',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  standard_trader: {
    id: 'standard_trader',
    name: 'Standard Trader',
    description: 'Classic professional trading interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#d1d4dc',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ef5350',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ef5350',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ef5350',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  military: {
    id: 'military',
    name: 'Military Veteran',
    description: 'Structured, tactical interface for veterans.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#94a3b8',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#1e293b',
      borderB: '#0f172a',
    },
    candles: {
      upColor: '#4D00FF',
      downColor: '#ef4444',
      wickUpColor: '#4D00FF',
      wickDownColor: '#ef4444',
      borderUpColor: '#4D00FF',
      borderDownColor: '#ef4444',
    },
    behavior: {
      glow: 'none',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'smooth',
    },
  },
};
