
import { GlowLevel, MotionLevel, NeuroProfile } from '../../types';

export const NEURO_PROFILES: Record<string, NeuroProfile> = {
  calm_focus: {
    id: 'calm_focus',
    name: 'Calm Focus',
    description: 'Reduced stimulus for deep concentration.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#a0a0b0',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#1e1e2e',
      borderB: '#161625',
    },
    candles: {
      upColor: '#4ade80',
      downColor: '#f87171',
      wickUpColor: '#4ade80',
      wickDownColor: '#f87171',
      borderUpColor: '#4ade80',
      borderDownColor: '#f87171',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  low_stim_emergency: {
    id: 'low_stim_emergency',
    name: 'Low Stim Emergency',
    description: 'Minimalist interface for high-stress moments.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#888888',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#222222',
      borderB: '#111111',
    },
    candles: {
      upColor: '#6b7280',
      downColor: '#9ca3af',
      wickUpColor: '#6b7280',
      wickDownColor: '#9ca3af',
      borderUpColor: '#6b7280',
      borderDownColor: '#9ca3af',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  dyslexia_readable: {
    id: 'dyslexia_readable',
    name: 'Dyslexia Readable',
    description: 'High legibility and visual grounding.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#34d399',
      downColor: '#fbbf24',
      wickUpColor: '#34d399',
      wickDownColor: '#fbbf24',
      borderUpColor: '#34d399',
      borderDownColor: '#fbbf24',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  dyscalculia_numeric_relief: {
    id: 'dyscalculia_numeric_relief',
    name: 'Dyscalculia Numeric Relief',
    description: 'Visual-first data with reduced numeric strain.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#60a5fa',
      downColor: '#f472b6',
      wickUpColor: '#60a5fa',
      wickDownColor: '#f472b6',
      borderUpColor: '#60a5fa',
      borderDownColor: '#f472b6',
    },
    behavior: {
      glow: 'medium',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  visual_processing_safe: {
    id: 'visual_processing_safe',
    name: 'Visual Processing Safe',
    description: 'Stable, flicker-free rendering.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#d1d1d1',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#2dd4bf',
      downColor: '#fb923c',
      wickUpColor: '#2dd4bf',
      wickDownColor: '#fb923c',
      borderUpColor: '#2dd4bf',
      borderDownColor: '#fb923c',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'static',
    },
  },
  apd_assist: {
    id: 'apd_assist',
    name: 'APD Assist',
    description: 'Visual cues for auditory events.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#e94560',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#533483',
    },
    candles: {
      upColor: '#a78bfa',
      downColor: '#fb7185',
      wickUpColor: '#a78bfa',
      wickDownColor: '#fb7185',
      borderUpColor: '#a78bfa',
      borderDownColor: '#fb7185',
    },
    behavior: {
      glow: 'low',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  executive_function_support: {
    id: 'executive_function_support',
    name: 'Executive Function Support',
    description: 'Simplified flow and clear visual hierarchy.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#818cf8',
      downColor: '#34d399',
      wickUpColor: '#818cf8',
      wickDownColor: '#34d399',
      borderUpColor: '#818cf8',
      borderDownColor: '#34d399',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  motor_friendly: {
    id: 'motor_friendly',
    name: 'Motor Friendly',
    description: 'Large targets and simplified interactions.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#3b82f6',
      downColor: '#ef4444',
      wickUpColor: '#3b82f6',
      wickDownColor: '#ef4444',
      borderUpColor: '#3b82f6',
      borderDownColor: '#ef4444',
    },
    behavior: {
      glow: 'medium',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  adhd_dopamine_balanced: {
    id: 'adhd_dopamine_balanced',
    name: 'ADHD Dopamine Balanced',
    description: 'Engaging but structured visual feedback.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#4D00FF',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#fcd34d',
      downColor: '#c084fc',
      wickUpColor: '#fcd34d',
      wickDownColor: '#c084fc',
      borderUpColor: '#fcd34d',
      borderDownColor: '#c084fc',
    },
    behavior: {
      glow: 'high',
      spacing: 'normal',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  adhd_hyperfocus: {
    id: 'adhd_hyperfocus',
    name: 'ADHD Hyperfocus',
    description: 'High-velocity pattern detection mode.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#FF007F',
      downColor: '#0000FF',
      wickUpColor: '#FF007F',
      wickDownColor: '#0000FF',
      borderUpColor: '#FF007F',
      borderDownColor: '#0000FF',
    },
    behavior: {
      glow: 'high',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  autism_predictable: {
    id: 'autism_predictable',
    name: 'Autism Predictable',
    description: 'Stable, symmetrical, and consistent interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#eeeeee',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#000000',
    },
    candles: {
      upColor: '#6ee7b7',
      downColor: '#9ca3af',
      wickUpColor: '#6ee7b7',
      wickDownColor: '#9ca3af',
      borderUpColor: '#6ee7b7',
      borderDownColor: '#9ca3af',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  tourette_tic_friendly: {
    id: 'tourette_tic_friendly',
    name: 'Tourette Tic Friendly',
    description: 'Low-surprise UI with stable visual rhythm.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#bbe1fa',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#38bdf8',
      downColor: '#94a3b8',
      wickUpColor: '#38bdf8',
      wickDownColor: '#94a3b8',
      borderUpColor: '#38bdf8',
      borderDownColor: '#94a3b8',
    },
    behavior: {
      glow: 'low',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  plain_language: {
    id: 'plain_language',
    name: 'Plain Language',
    description: 'Simplified terminology and clear visual cues.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#10b981',
      downColor: '#dc2626',
      wickUpColor: '#10b981',
      wickDownColor: '#dc2626',
      borderUpColor: '#10b981',
      borderDownColor: '#dc2626',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  high_contrast: {
    id: 'high_contrast',
    name: 'High Contrast',
    description: 'Maximum visual separation for clarity.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#000000',
      text: '#ffff00',
      accent: '#4D00FF',
      gridColor: 'rgba(255, 255, 255, 0.2)',
      borderA: '#ffffff',
      borderB: '#ffffff',
    },
    candles: {
      upColor: '#00ff00',
      downColor: '#ff0000',
      wickUpColor: '#00ff00',
      wickDownColor: '#ff0000',
      borderUpColor: '#00ff00',
      borderDownColor: '#ff0000',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'static',
    },
  },
  custom_neuro_mix: {
    id: 'custom_neuro_mix',
    name: 'Custom Neuro Mix',
    description: 'Balanced hybrid for mixed neuro-types.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#e0e0e0',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#8b5cf6',
      downColor: '#f97316',
      wickUpColor: '#8b5cf6',
      wickDownColor: '#f97316',
      borderUpColor: '#8b5cf6',
      borderDownColor: '#f97316',
    },
    behavior: {
      glow: 'low',
      spacing: 'relaxed',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  corporate_open: {
    id: 'corporate_open',
    name: 'Corporate Open',
    description: 'Clean, professional multi-chart layout.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#0284c7',
      downColor: '#be123c',
      wickUpColor: '#0284c7',
      wickDownColor: '#be123c',
      borderUpColor: '#0284c7',
      borderDownColor: '#be123c',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'high',
      motion: 'smooth',
    },
  },
  retail_chaos: {
    id: 'retail_chaos',
    name: 'Retail Chaos',
    description: 'High-intensity, high-information density.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#4D00FF',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#ff00ff',
    },
    candles: {
      upColor: '#16a34a',
      downColor: '#dc2626',
      wickUpColor: '#16a34a',
      wickDownColor: '#dc2626',
      borderUpColor: '#16a34a',
      borderDownColor: '#dc2626',
    },
    behavior: {
      glow: 'high',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'dynamic',
    },
  },
  retail_modular: {
    id: 'retail_modular',
    name: 'Retail Modular',
    description: 'Flexible, widget-based interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.05)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#0891b2',
      downColor: '#e11d48',
      wickUpColor: '#0891b2',
      wickDownColor: '#e11d48',
      borderUpColor: '#0891b2',
      borderDownColor: '#e11d48',
    },
    behavior: {
      glow: 'none',
      spacing: 'relaxed',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  vr_assistive: {
    id: 'vr_assistive',
    name: 'VR Assistive',
    description: 'Optimized for spatial computing and depth.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: 'rgba(0, 0, 0, 0.5)',
      text: '#ffffff',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#c026d3',
      downColor: '#0284c7',
      wickUpColor: '#c026d3',
      wickDownColor: '#0284c7',
      borderUpColor: '#c026d3',
      borderDownColor: '#0284c7',
    },
    behavior: {
      glow: 'high',
      spacing: 'relaxed',
      dataDensity: 'low',
      motion: 'smooth',
    },
  },
  standard_trader: {
    id: 'standard_trader',
    name: 'Standard Trader',
    description: 'Classic professional trading interface.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#d1d4dc',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#4D00FF',
      borderB: '#4D00FF',
    },
    candles: {
      upColor: '#22c55e',
      downColor: '#ef4444',
      wickUpColor: '#22c55e',
      wickDownColor: '#ef4444',
      borderUpColor: '#22c55e',
      borderDownColor: '#ef4444',
    },
    behavior: {
      glow: 'none',
      spacing: 'normal',
      dataDensity: 'normal',
      motion: 'smooth',
    },
  },
  military: {
    id: 'military',
    name: 'Military Veteran',
    description: 'Structured, tactical interface for veterans.',
    ui: {
      bgTop: '#000000',
      bgBottom: '#000000',
      panel: '#0a0a0a',
      text: '#94a3b8',
      accent: '#4D00FF',
      gridColor: 'rgba(77, 0, 255, 0.1)',
      borderA: '#1e293b',
      borderB: '#0f172a',
    },
    candles: {
      upColor: '#4d7c0f',
      downColor: '#7f1d1d',
      wickUpColor: '#4d7c0f',
      wickDownColor: '#7f1d1d',
      borderUpColor: '#4d7c0f',
      borderDownColor: '#7f1d1d',
    },
    behavior: {
      glow: 'none',
      spacing: 'tight',
      dataDensity: 'high',
      motion: 'smooth',
    },
  },
};
