export type NeuroProfileId =
  | "calm_focus"
  | "low_stim_emergency"
  | "dyslexia_readable"
  | "dyscalculia_numeric_relief"
  | "visual_processing_safe"
  | "apd_assist"
  | "executive_function_support"
  | "motor_friendly"
  | "adhd_dopamine_balanced"
  | "adhd_hyperfocus"
  | "autism_predictable"
  | "tourette_tic_friendly"
  | "plain_language"
  | "high_contrast"
  | "custom_neuro_mix"
  | "corporate_open"
  | "retail_chaos"
  | "retail_modular"
  | "vr_assistive"
  | "standard_trader";

export type NeuroProfile = {
  id: NeuroProfileId;
  label: string;
  bgTop: string;
  bgBottom: string;
  panel: string;
  text: string;
  grid: string;
  borderA: string;
  borderB: string;
  upColor: string;
  downColor: string;
  wickUpColor: string;
  wickDownColor: string;
  borderUpColor: string;
  borderDownColor: string;
  glow: "Low" | "Medium" | "High";
  spacing: "Tight" | "Normal" | "Wide";
  dataDensity: "Low" | "Medium" | "High";
  motion: "Off" | "Soft" | "Normal";
};

export const neuroProfiles: Record<NeuroProfileId, NeuroProfile> = {
  calm_focus: {
    id: "calm_focus",
    label: "Calm Focus",
    bgTop: "#07111f",
    bgBottom: "#030712",
    panel: "rgba(8,15,28,0.92)",
    text: "#dbeafe",
    grid: "rgba(125,211,252,0.15)",
    borderA: "#38bdf8",
    borderB: "#a78bfa",
    upColor: "#67e8f9",
    downColor: "#a78bfa",
    wickUpColor: "#93c5fd",
    wickDownColor: "#c4b5fd",
    borderUpColor: "#67e8f9",
    borderDownColor: "#a78bfa",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  low_stim_emergency: {
    id: "low_stim_emergency",
    label: "Low Stimulation",
    bgTop: "#05070b",
    bgBottom: "#000000",
    panel: "rgba(5,7,11,0.96)",
    text: "#cbd5e1",
    grid: "rgba(148,163,184,0.08)",
    borderA: "#475569",
    borderB: "#64748b",
    upColor: "#94a3b8",
    downColor: "#64748b",
    wickUpColor: "#94a3b8",
    wickDownColor: "#64748b",
    borderUpColor: "#94a3b8",
    borderDownColor: "#64748b",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  dyslexia_readable: {
    id: "dyslexia_readable",
    label: "Reading Support",
    bgTop: "#08131f",
    bgBottom: "#020617",
    panel: "rgba(8,19,31,0.92)",
    text: "#f8fafc",
    grid: "rgba(226,232,240,0.14)",
    borderA: "#34d399",
    borderB: "#60a5fa",
    upColor: "#34d399",
    downColor: "#f59e0b",
    wickUpColor: "#6ee7b7",
    wickDownColor: "#fbbf24",
    borderUpColor: "#34d399",
    borderDownColor: "#f59e0b",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Soft",
  },
  dyscalculia_numeric_relief: {
    id: "dyscalculia_numeric_relief",
    label: "Numeric Relief",
    bgTop: "#0a1220",
    bgBottom: "#020617",
    panel: "rgba(10,18,32,0.94)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.10)",
    borderA: "#22c55e",
    borderB: "#f59e0b",
    upColor: "#4ade80",
    downColor: "#fb7185",
    wickUpColor: "#86efac",
    wickDownColor: "#fda4af",
    borderUpColor: "#4ade80",
    borderDownColor: "#fb7185",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  visual_processing_safe: {
    id: "visual_processing_safe",
    label: "Visual Ease",
    bgTop: "#06111b",
    bgBottom: "#01040a",
    panel: "rgba(6,17,27,0.95)",
    text: "#dbeafe",
    grid: "rgba(147,197,253,0.08)",
    borderA: "#60a5fa",
    borderB: "#a78bfa",
    upColor: "#60a5fa",
    downColor: "#fca5a5",
    wickUpColor: "#93c5fd",
    wickDownColor: "#fecaca",
    borderUpColor: "#60a5fa",
    borderDownColor: "#fca5a5",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  apd_assist: {
    id: "apd_assist",
    label: "Reduced Signal Load",
    bgTop: "#08131d",
    bgBottom: "#020617",
    panel: "rgba(8,19,29,0.93)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.14)",
    borderA: "#2dd4bf",
    borderB: "#fb7185",
    upColor: "#2dd4bf",
    downColor: "#fb7185",
    wickUpColor: "#5eead4",
    wickDownColor: "#fda4af",
    borderUpColor: "#2dd4bf",
    borderDownColor: "#fb7185",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Soft",
  },
  executive_function_support: {
    id: "executive_function_support",
    label: "Task Structure",
    bgTop: "#07101b",
    bgBottom: "#020617",
    panel: "rgba(7,16,27,0.94)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.10)",
    borderA: "#38bdf8",
    borderB: "#f97316",
    upColor: "#38bdf8",
    downColor: "#f97316",
    wickUpColor: "#7dd3fc",
    wickDownColor: "#fdba74",
    borderUpColor: "#38bdf8",
    borderDownColor: "#f97316",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  motor_friendly: {
    id: "motor_friendly",
    label: "Large Target Mode",
    bgTop: "#09111f",
    bgBottom: "#020617",
    panel: "rgba(9,17,31,0.94)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.12)",
    borderA: "#34d399",
    borderB: "#f87171",
    upColor: "#34d399",
    downColor: "#f87171",
    wickUpColor: "#86efac",
    wickDownColor: "#fca5a5",
    borderUpColor: "#34d399",
    borderDownColor: "#f87171",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  adhd_dopamine_balanced: {
    id: "adhd_dopamine_balanced",
    label: "Balanced Energy",
    bgTop: "#09091b",
    bgBottom: "#020617",
    panel: "rgba(9,9,27,0.93)",
    text: "#f8fafc",
    grid: "rgba(34,211,238,0.16)",
    borderA: "#22d3ee",
    borderB: "#f472b6",
    upColor: "#22d3ee",
    downColor: "#f472b6",
    wickUpColor: "#67e8f9",
    wickDownColor: "#f9a8d4",
    borderUpColor: "#22d3ee",
    borderDownColor: "#f472b6",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Normal",
  },
  adhd_hyperfocus: {
    id: "adhd_hyperfocus",
    label: "Hyperfocus",
    bgTop: "#090510",
    bgBottom: "#000000",
    panel: "rgba(9,5,16,0.95)",
    text: "#ffffff",
    grid: "rgba(255,212,0,0.16)",
    borderA: "#00f5ff",
    borderB: "#ff3dff",
    upColor: "#00f5ff",
    downColor: "#ff3dff",
    wickUpColor: "#9bf6ff",
    wickDownColor: "#ffb3ff",
    borderUpColor: "#00f5ff",
    borderDownColor: "#ff3dff",
    glow: "High",
    spacing: "Tight",
    dataDensity: "High",
    motion: "Normal",
  },
  autism_predictable: {
    id: "autism_predictable",
    label: "Autism - Predictable",
    bgTop: "#07111a",
    bgBottom: "#020617",
    panel: "rgba(7,17,26,0.94)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.14)",
    borderA: "#86efac",
    borderB: "#93c5fd",
    upColor: "#86efac",
    downColor: "#93c5fd",
    wickUpColor: "#bbf7d0",
    wickDownColor: "#bfdbfe",
    borderUpColor: "#86efac",
    borderDownColor: "#93c5fd",
    glow: "Low",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Off",
  },
  tourette_tic_friendly: {
    id: "tourette_tic_friendly",
    label: "Minimal Motion",
    bgTop: "#05070b",
    bgBottom: "#000000",
    panel: "rgba(5,7,11,0.96)",
    text: "#e2e8f0",
    grid: "rgba(148,163,184,0.08)",
    borderA: "#a7f3d0",
    borderB: "#fbcfe8",
    upColor: "#a7f3d0",
    downColor: "#fbcfe8",
    wickUpColor: "#d1fae5",
    wickDownColor: "#fce7f3",
    borderUpColor: "#a7f3d0",
    borderDownColor: "#fbcfe8",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Off",
  },
  plain_language: {
    id: "plain_language",
    label: "Plain Language",
    bgTop: "#08131f",
    bgBottom: "#020617",
    panel: "rgba(8,19,31,0.93)",
    text: "#f8fafc",
    grid: "rgba(148,163,184,0.10)",
    borderA: "#4ade80",
    borderB: "#60a5fa",
    upColor: "#4ade80",
    downColor: "#fca5a5",
    wickUpColor: "#86efac",
    wickDownColor: "#fecaca",
    borderUpColor: "#4ade80",
    borderDownColor: "#fca5a5",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  high_contrast: {
    id: "high_contrast",
    label: "High Contrast",
    bgTop: "#000000",
    bgBottom: "#000000",
    panel: "rgba(0,0,0,0.98)",
    text: "#ffffff",
    grid: "rgba(255,255,255,0.18)",
    borderA: "#f97316",
    borderB: "#ffffff",
    upColor: "#ffffff",
    downColor: "#f97316",
    wickUpColor: "#ffffff",
    wickDownColor: "#fed7aa",
    borderUpColor: "#ffffff",
    borderDownColor: "#f97316",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Off",
  },
  custom_neuro_mix: {
    id: "custom_neuro_mix",
    label: "Custom Mix",
    bgTop: "#08111d",
    bgBottom: "#020617",
    panel: "rgba(8,17,29,0.93)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.14)",
    borderA: "#60a5fa",
    borderB: "#f472b6",
    upColor: "#60a5fa",
    downColor: "#f472b6",
    wickUpColor: "#93c5fd",
    wickDownColor: "#f9a8d4",
    borderUpColor: "#60a5fa",
    borderDownColor: "#f472b6",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Soft",
  },
  corporate_open: {
    id: "corporate_open",
    label: "Corporate Open",
    bgTop: "#071018",
    bgBottom: "#020617",
    panel: "rgba(7,16,24,0.95)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.10)",
    borderA: "#7dd3fc",
    borderB: "#a78bfa",
    upColor: "#7dd3fc",
    downColor: "#fde68a",
    wickUpColor: "#bae6fd",
    wickDownColor: "#fef3c7",
    borderUpColor: "#7dd3fc",
    borderDownColor: "#fde68a",
    glow: "Low",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Off",
  },
  retail_chaos: {
    id: "retail_chaos",
    label: "HFT Scanner",
    bgTop: "#090510",
    bgBottom: "#000000",
    panel: "rgba(9,5,16,0.95)",
    text: "#ffffff",
    grid: "rgba(255,255,255,0.10)",
    borderA: "#00f5ff",
    borderB: "#ff3dff",
    upColor: "#00f5ff",
    downColor: "#ff3dff",
    wickUpColor: "#9bf6ff",
    wickDownColor: "#ffb3ff",
    borderUpColor: "#00f5ff",
    borderDownColor: "#ff3dff",
    glow: "High",
    spacing: "Tight",
    dataDensity: "High",
    motion: "Normal",
  },
  retail_modular: {
    id: "retail_modular",
    label: "Retail Modular",
    bgTop: "#07111f",
    bgBottom: "#020617",
    panel: "rgba(7,17,31,0.93)",
    text: "#f8fafc",
    grid: "rgba(148,163,184,0.14)",
    borderA: "#22d3ee",
    borderB: "#f59e0b",
    upColor: "#22d3ee",
    downColor: "#f59e0b",
    wickUpColor: "#67e8f9",
    wickDownColor: "#fcd34d",
    borderUpColor: "#22d3ee",
    borderDownColor: "#f59e0b",
    glow: "Medium",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Normal",
  },
  vr_assistive: {
    id: "vr_assistive",
    label: "VR Assistive",
    bgTop: "#050816",
    bgBottom: "#01040a",
    panel: "rgba(5,8,22,0.94)",
    text: "#e0f2fe",
    grid: "rgba(125,211,252,0.10)",
    borderA: "#38bdf8",
    borderB: "#22c55e",
    upColor: "#38bdf8",
    downColor: "#22c55e",
    wickUpColor: "#7dd3fc",
    wickDownColor: "#86efac",
    borderUpColor: "#38bdf8",
    borderDownColor: "#22c55e",
    glow: "Low",
    spacing: "Wide",
    dataDensity: "Low",
    motion: "Soft",
  },
  standard_trader: {
    id: "standard_trader",
    label: "Standard Trader",
    bgTop: "#071018",
    bgBottom: "#020617",
    panel: "rgba(7,16,24,0.95)",
    text: "#f1f5f9",
    grid: "rgba(148,163,184,0.12)",
    borderA: "#22c55e",
    borderB: "#ef4444",
    upColor: "#22c55e",
    downColor: "#ef4444",
    wickUpColor: "#86efac",
    wickDownColor: "#fca5a5",
    borderUpColor: "#22c55e",
    borderDownColor: "#ef4444",
    glow: "Low",
    spacing: "Normal",
    dataDensity: "Medium",
    motion: "Off",
  },
};
